//132
// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;

[assembly: AssemblyFileVersion("2.4.99.132")]
[assembly: AssemblyVersion("2.4.99.1")]
[assembly: AssemblyInformationalVersion("2.4.99")]
[assembly: KSPAssembly("PreciseManeuver", 2,4,99)]

namespace KSPPreciseManeuver
{
	public static class Version
	{
		public const int major = 2;
		public const int minor = 4;
		public const int patch = 99;
		public const int build = 1;
		public const string Number = "2.4.99.1";
#if DEBUG
        public const string Text = Number + "-zed'K BETA DEBUG";
        public const string SText = Number + "-zed'K BETA DEBUG";
#else
        public const string Text = Number + "-zed'K";
		public const string SText = Number;
#endif
	}
}